// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VisualProtobuf.Extensions {

  /// <summary>Holder for reflection information generated from options.proto</summary>
  public static partial class OptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1vcHRpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5w",
            "cm90bzo7ChNmaWVsZF9vcHRpb25fc3RyaW5nEh0uZ29vZ2xlLnByb3RvYnVm",
            "LkZpZWxkT3B0aW9ucxiRTiABKAlCHKoCGVZpc3VhbFByb3RvYnVmLkV4dGVu",
            "c2lvbnM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionsExtensions.FieldOptionString }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of options.proto</summary>
  public static partial class OptionsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> FieldOptionString =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(10001, pb::FieldCodec.ForString(80010, ""));
  }

}

#endregion Designer generated code
